const mongoose = require('mongoose');
module.exports = {
    tbl_balance_sheet_group_mst: new mongoose.Schema({
        id: { type: Number, required: true, default: 0 },
        balance_sheet_group_id: { type: Number, required: false },
        balance_sheet_group_name: { type: String, required: false },
        is_deleted: { type: Number, required: false },
    }).set("collection", "tbl_balance_sheet_group_mst").set("autoIndex", true),
    tbl_company_branch: new mongoose.Schema({
        company_branch_id: { type: Number, required: false },
        company_id: { type: Number, required: false },
        name: { type: String, required: false },
        companyid_ref: { type: mongoose.Schema.Types.ObjectId, ref: "tbl_company_mst", required: false },
        is_deleted: { type: Number, required: false },
    }).set("collection", "tbl_company_branch").set("autoIndex", true),
    tbl_company_mst: new mongoose.Schema({
        company_id: { type: Number, required: false },
        company_name: { type: String, required: false },
        company_code: { type: String, required: false },
        typeofcustomer_id: { type: Number, required: false },
        is_deleted: { type: Number, required: false }
    }).set("collection", "tbl_company_mst").set("autoIndex", true),
    tbl_financial_year_mst: new mongoose.Schema({
        financial_year_id: { type: Number, required: false },
        financial_year: { type: String, required: false },
        start_date: { type: Date, required: false },
        end_date: { type: Date, required: false },
        company_id: { type: Number, required: false },
        is_deleted: { type: Number, required: false }
    }).set("collection", "tbl_financial_year_mst").set("autoIndex", true),
    tbl_general_ledger_mst: new mongoose.Schema({
        gl_id: { type: Number, required: false, default: 0 },
        gl_desc: { type: String, required: false },
        gl_code: { type: String, required: false },
        gl_type: { type: Number, required: false },
        tb_group_id: { type: Number, required: false },
        fin_year_id: { type: Number, required: false },
        company_id: { type: Number, required: false },
        company_branch_id: { type: Number, required: false },
        is_deleted: { type: Number, required: false }
    }).set("collection", "tbl_general_ledger_mst").set("autoIndex", true),
    tbl_gl_balance_mst: new mongoose.Schema({
        gl_bal_id: { type: Number, required: false, default: 0 },
        gl_id: { type: Number, required: false },
        gl_ref_id: { type: mongoose.Schema.Types.ObjectId,ref: "tbl_general_ledger_mst" ,required: false },
        op_bal: { type: Number, required: false },
        fin_year_id: { type: Number, required: false },
        company_id: { type: Number, required: false },
        company_branch_id: { type: Number, required: false },
        op_bal_cr: { type: Number, required: false },
        is_deleted: { type: Number, required: false },
        party_op_bal_dr: { type: Number, required: false },
        party_op_bal_cr: { type: Number, required: false },
        currency_id: { type: Number, required: false },
        party_op_bal_dr_fc: { type: Number, required: false },
        party_op_bal_cr_fc: { type: Number, required: false },
    }).set("collection", "tbl_gl_balance_mst").set("autoIndex", true),
    tbl_gl_branch: new mongoose.Schema({
        gl_branch_id: { type: Number, required: false, default: 0 },
        gl_id: { type: Number, required: false },
        gl_ref_id: { type: mongoose.Schema.Types.ObjectId,ref: "tbl_general_ledger_mst" ,required: false },
        branch_id: { type: Number, required: false },
        is_deleted: { type: Number, required: false }
    }).set("collection", "tbl_gl_branch").set("autoIndex", true),
    tbl_tb_group_mst: new mongoose.Schema({
        tb_group_id: { type: Number, required: false },
        tb_group_name: { type: String, required: false },
        tb_group_code: { type: String, required: false },
        under_group_id: { type: Number, required: false },
        parent_group_id: { type: Number, required: false },
        fin_year_id: { type: Number, required: false },
        company_id: { type: Number, required: false },
        is_deleted: { type: Number, required: false },
        parent_group: { type: String, required: false },
        detailed: { type: String, required: false },
        display_sr_no: { type: Number, required: false }
    }).set("collection", "tbl_tb_group_mst").set("autoIndex", true),
    tbl_voucher: new mongoose.Schema({
        voucher_id: { type: Number, required: false },
        Voucher_type: { type: String, required: false },
        Voucher_date: { type: Date, required: false },
        Company_id: { type: Number, required: false },
        Company_Branch_id: { type: Number, required: false },
        Fin_year: { type: Number, required: false },
        generated_voucher_No: { type: String, required: false },
        transaction_status: { type: String, required: false },
        account_effect: { type: String, required: false },
        is_deleted: { type: Number, required: false },
    }).set("collection", "tbl_voucher").set("autoIndex", true),
    tbl_voucher_ledger: new mongoose.Schema({
        voucher_ledger_id: { type: Number, required: false },
        voucher_id: { type: Number, required: false },
        Voucher_ref_id: { type: mongoose.Schema.Types.ObjectId,ref: "tbl_voucher" ,required: false },
        gl_account: { type: Number, required: false },
        Debit_Amount: { type: Number, required: false },
        Credit_Amount: { type: Number, required: false },
        is_deleted: { type: Number, required: false },
        debit_amount_fc: { type: Number, required: false },
        credit_amount_fc: { type: Number, required: false },
    }).set("collection", "tbl_voucher_ledger").set("autoIndex", true),
}